#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
  for DIR in `ls -d /usr/share/icons/FreedomOS-Cursors-*`; do
    update-icon-caches /usr/share/icons/$DIR -f
  done
fi
# End automatically added section
