#!/bin/sh
set -e

# Automatically added by dh_icons
case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        if which update-icon-caches >/dev/null 2>&1 ; then
            for DIR in `ls -d /usr/share/icons/*`; do
                update-icon-caches /usr/share/icons/$DIR -f
            done
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
# End automatically added section


#DEBHELPER#

exit 0
