#!/bin/sh
set -e

case "$1" in
    configure)
        if which update-icon-caches >/dev/null 2>&1
        then
            update-icon-caches -f /usr/share/icons/Sucharu*
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
